//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintAssistConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal test() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintAssistConsole.Properties.test", typeof(test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aktiviert ähnelt.
        /// </summary>
        public static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Kalibrierung ist abgeschlossen. Der Drucker heizt auf seine finale Betriebstempertur auf. Es geht gleich los. ähnelt.
        /// </summary>
        public static string CalibrationFinished {
            get {
                return ResourceManager.GetString("CalibrationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erklärung abbrechen ähnelt.
        /// </summary>
        public static string CancelExplanation {
            get {
                return ResourceManager.GetString("CancelExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktueller Status: ähnelt.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deaktiviert ähnelt.
        /// </summary>
        public static string deactivated {
            get {
                return ResourceManager.GetString("deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hi. Ich bin dein persönlicher 3D Druckassistent. Ich kann dir den Drucker und den 3D Druck Workflow erklären, 3D Modelle im Internet für dich suchen, Modelle für den Drucker vorbereiten und den Druck starten. ähnelt.
        /// </summary>
        public static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für feine Details veringere ich die Druckgeschwindigkeit etwas. ähnelt.
        /// </summary>
        public static string GuidedFineDetails {
            get {
                return ResourceManager.GetString("GuidedFineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehr Infill wird die Stabilität des Objets erhöhen. ähnelt.
        /// </summary>
        public static string GuidedMoreInfill {
            get {
                return ResourceManager.GetString("GuidedMoreInfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay, dann können wir mit normaler Druckgegeschwindigkeit drucken. ähnelt.
        /// </summary>
        public static string GuidedNoFineDetails {
            get {
                return ResourceManager.GetString("GuidedNoFineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay, dann reicht ein geringerer Füllgrad von 15%. ähnelt.
        /// </summary>
        public static string GuidedNormalInfill {
            get {
                return ResourceManager.GetString("GuidedNormalInfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei Objekten ohne Überhängen können Supportstrukturen deaktiviert werden. ähnelt.
        /// </summary>
        public static string GuidedSupportOff {
            get {
                return ResourceManager.GetString("GuidedSupportOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei Objekten mit Überhängen sollten Supportstrukturen aktiviert werden. ähnelt.
        /// </summary>
        public static string GuidedSupportOn {
            get {
                return ResourceManager.GetString("GuidedSupportOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay, dann reicht eine höhere Schichthöhe von 0,25 mm ähnelt.
        /// </summary>
        public static string GuidedSurfaceNormal {
            get {
                return ResourceManager.GetString("GuidedSurfaceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für eine glatte Oberfläche wähle ich eine geringe Schichthöhe von 0,1 mm. ähnelt.
        /// </summary>
        public static string GuidedSurfaceSmooth {
            get {
                return ResourceManager.GetString("GuidedSurfaceSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .\BotContent\HardwareTutorial_de.json ähnelt.
        /// </summary>
        public static string HardwareTutorialFilePath {
            get {
                return ResourceManager.GetString("HardwareTutorialFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Druck fährt nun zu seiner Startposition und führt anschließend seine automatische Kalibrierung aus. ähnelt.
        /// </summary>
        public static string Homing {
            get {
                return ResourceManager.GetString("Homing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füllgrad ähnelt.
        /// </summary>
        public static string InfillPercentage {
            get {
                return ResourceManager.GetString("InfillPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Eingabe nicht gültig. Das Infill muss zwischen 0% und 100% betragen. ähnelt.
        /// </summary>
        public static string InvalidInfillPercentage {
            get {
                return ResourceManager.GetString("InvalidInfillPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle eine Füllmenge aus der Auswahl unten aus oder gibt die Zahl in Prozent ein. ähnelt.
        /// </summary>
        public static string InvalidInfillPercentageFormat {
            get {
                return ResourceManager.GetString("InvalidInfillPercentageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Eingabe nicht gültig. Die Layer Height muss zwischen 0,05 mm und 0.3 mm betragen. ähnelt.
        /// </summary>
        public static string InvalidLayerHeight {
            get {
                return ResourceManager.GetString("InvalidLayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle eine Layer Height aus der Auswahl unten aus oder gibt die Zahl in Millimeter ein. ähnelt.
        /// </summary>
        public static string InvalidLayerHeightFormat {
            get {
                return ResourceManager.GetString("InvalidLayerHeightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Profil. ähnelt.
        /// </summary>
        public static string InvalidProfile {
            get {
                return ResourceManager.GetString("InvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schichthöhe ähnelt.
        /// </summary>
        public static string LayerHeight {
            get {
                return ResourceManager.GetString("LayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Düse ähnelt.
        /// </summary>
        public static string Nozzle {
            get {
                return ResourceManager.GetString("Nozzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht zu den wichtigsten Parametern: ähnelt.
        /// </summary>
        public static string ParameterSummary {
            get {
                return ResourceManager.GetString("ParameterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Druckdauer ähnelt.
        /// </summary>
        public static string PrintDuration {
            get {
                return ResourceManager.GetString("PrintDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es geht los! ähnelt.
        /// </summary>
        public static string PrintStarting {
            get {
                return ResourceManager.GetString("PrintStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortschritt ähnelt.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restliche Druckdauer ähnelt.
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du die Datei jetzt slicen und drucken? ähnelt.
        /// </summary>
        public static string SliceNowQuestion {
            get {
                return ResourceManager.GetString("SliceNowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .\BotContent\SlicingProcess_de.json ähnelt.
        /// </summary>
        public static string SlicingDialogDataPath {
            get {
                return ResourceManager.GetString("SlicingDialogDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slicing abgeschlossen. ähnelt.
        /// </summary>
        public static string SlicingFinished {
            get {
                return ResourceManager.GetString("SlicingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slicing läuft ähnelt.
        /// </summary>
        public static string SlicingInProgress {
            get {
                return ResourceManager.GetString("SlicingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähe einen Slicingmode aus [Expert/Beginner] oder sag abbrechen, wenn du den Vorgang abbrechen möchtest. ähnelt.
        /// </summary>
        public static string SlicingModeSelection {
            get {
                return ResourceManager.GetString("SlicingModeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was kann ich für dich tun? ähnelt.
        /// </summary>
        public static string StartIdleMessage {
            get {
                return ResourceManager.GetString("StartIdleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich hab dein Modell erhalten. Möchtest du das Modell jetzt slicen? ähnelt.
        /// </summary>
        public static string StlRecieved {
            get {
                return ResourceManager.GetString("StlRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay, ich passe auf die Datei auf. Du kannst mich später nochmal fragen. ähnelt.
        /// </summary>
        public static string StoringFile {
            get {
                return ResourceManager.GetString("StoringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supportstrukturen ähnelt.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supportstrukturen ähnelt.
        /// </summary>
        public static string SupportIs {
            get {
                return ResourceManager.GetString("SupportIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benötigtes Filament ähnelt.
        /// </summary>
        public static string UsedFilament {
            get {
                return ResourceManager.GetString("UsedFilament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .\BotContent\WorkflowTutorial_de.json ähnelt.
        /// </summary>
        public static string WorkflowTutorialFilePath {
            get {
                return ResourceManager.GetString("WorkflowTutorialFilePath", resourceCulture);
            }
        }
    }
}
